// Characterization replay tests (Task 8, Phase 1 capstone).
//
// Fixtures under `test/fixtures/*.json` are byte-for-byte copies of
// `FortyTwo.Tests/Characterization/Fixtures/*.json`, generated by running the REAL C#
// `MatchService` through hand-scripted scenarios (`FortyTwo.Tests/Characterization/
// {StandardGameScenarioTests,LowGameScenarioTests,PlungeScenarioTests}.cs`). Each fixture is an
// ordered array of `{ action, state }` steps recording the exact `MatchState` snapshot the real
// engine produced after each action.
//
// This suite replays the *same* action sequences (player ids, bids, dominoes, deal order)
// against the TS port's `matchEngine.ts` functions and asserts the resulting state matches the
// fixture's recorded state at every step. This is the actual proof that the TS port agrees with
// the real game engine - not just that it's internally self-consistent (which the other *.test.ts
// files in src/ already establish).
//
// Only meaningful game-state fields are compared: `currentGame.trump`, `.currentPlayerId`,
// `.biddingPlayerId`, `.bid`, `.tricks.length`, and each hand's `dominoes.length` (compared
// against the fixture's `dominos.length` - a typo preserved verbatim in the real C# JSON output).
// C#'s EF-only fields (`id`, `createdOn`, `updatedOn`, `match`, domino `orientation`/`order`/
// numeric `id`) have no TS equivalent and are deliberately not asserted on.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { Bid } from '../src/bid';
import { createDomino, Domino } from '../src/domino';
import { gameWinningTeam } from '../src/game';
import { addPlayer, createMatch, MatchState, placeBid, playDomino, setTrump } from '../src/matchEngine';
import { Suit } from '../src/suit';
import { Teams } from '../src/teams';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface FixtureStep {
  action: string;
  state: {
    currentGame: {
      trump: number | null;
      currentPlayerId: string | null;
      biddingPlayerId: string | null;
      bid: number | null;
      tricks: unknown[];
      hands: { playerId: string; dominos: unknown[] }[];
    };
  };
}

function loadFixture(name: string): FixtureStep[] {
  const path = join(__dirname, 'fixtures', name);
  return JSON.parse(readFileSync(path, 'utf-8')) as FixtureStep[];
}

function dealOrderFrom(tuples: [number, number][]): Domino[] {
  return tuples.map(([top, bottom]) => createDomino(top, bottom));
}

// Asserts the meaningful subset of `match`'s state against one fixture step's recorded `state`.
function expectMatchesFixtureStep(match: MatchState, step: FixtureStep, label: string): void {
  const fg = step.state.currentGame;

  expect(match.currentGame.trump, `${label}: trump`).toBe(fg.trump);
  expect(match.currentGame.currentPlayerId, `${label}: currentPlayerId`).toBe(fg.currentPlayerId);
  expect(match.currentGame.biddingPlayerId, `${label}: biddingPlayerId`).toBe(fg.biddingPlayerId);
  expect(match.currentGame.bid, `${label}: bid`).toBe(fg.bid);
  expect(match.currentGame.tricks.length, `${label}: tricks.length`).toBe(fg.tricks.length);

  for (const fixtureHand of fg.hands) {
    const hand = match.currentGame.hands.find((h) => h.playerId === fixtureHand.playerId);
    expect(hand, `${label}: hand for ${fixtureHand.playerId} exists`).toBeDefined();
    expect(hand!.dominoes.length, `${label}: ${fixtureHand.playerId} dominoes.length`).toBe(
      fixtureHand.dominos.length
    );
  }
}

describe('characterization: standard-game fixture', () => {
  const steps = loadFixture('standard-game.json');
  const dealOrder = dealOrderFrom([
    [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6],
    [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [1, 2],
    [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [2, 5],
    [2, 6], [3, 4], [3, 5], [3, 6], [4, 5], [4, 6], [5, 6],
  ]);

  it('replays the exact C# scenario and matches recorded state at every step', () => {
    expect(steps).toHaveLength(25);
    let i = 0;

    let match = createMatch('p1');
    expectMatchesFixtureStep(match, steps[i++], 'create');

    match = addPlayer(match, 'p2', Teams.TeamB);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p2');

    match = addPlayer(match, 'p3', Teams.TeamA);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p3');

    match = addPlayer(match, 'p4', Teams.TeamB, dealOrder);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p4 (deal)');

    match = placeBid(match, 'p1', Bid.Thirty);
    expectMatchesFixtureStep(match, steps[i++], 'bid p1 Thirty');
    match = placeBid(match, 'p2', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p2 Pass');
    match = placeBid(match, 'p3', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p3 Pass');
    match = placeBid(match, 'p4', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p4 Pass');

    match = setTrump(match, 'p1', Suit.Sixes);
    expectMatchesFixtureStep(match, steps[i++], 'setTrump p1 Sixes');

    const plays: [string, [number, number]][] = [
      ['p1', [6, 6]], ['p2', [0, 6]], ['p3', [1, 6]], ['p4', [3, 6]],
      ['p1', [5, 5]], ['p2', [0, 5]], ['p3', [1, 5]], ['p4', [3, 5]],
      ['p1', [4, 4]], ['p2', [0, 4]], ['p3', [1, 4]], ['p4', [3, 4]],
      ['p1', [3, 3]], ['p2', [0, 3]], ['p3', [1, 3]], ['p4', [4, 6]],
    ];

    for (const [playerId, [top, bottom]] of plays) {
      match = playDomino(match, playerId, createDomino(top, bottom));
      expectMatchesFixtureStep(match, steps[i++], `playDomino ${playerId} {${top},${bottom}}`);
    }

    expect(i).toBe(steps.length);
    // Only 4 of the hand's 7 tricks were recorded - deliberately stopped short. Neither team
    // crosses a scoring threshold in 4 tricks.
    expect(gameWinningTeam(match.currentGame)).toBeNull();
  });
});

describe('characterization: low-game fixture', () => {
  const steps = loadFixture('low-game.json');
  const dealOrder = dealOrderFrom([
    [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6],
    [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [1, 2], [1, 6],
    [0, 6], [2, 5], [3, 4], [3, 6], [4, 5], [4, 6], [5, 6],
    [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 6], [3, 5],
  ]);

  it('replays the exact C# scenario, including the Low skip rule, and matches recorded state', () => {
    expect(steps).toHaveLength(15);
    let i = 0;

    let match = createMatch('p1');
    expectMatchesFixtureStep(match, steps[i++], 'create');

    match = addPlayer(match, 'p2', Teams.TeamB);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p2');

    match = addPlayer(match, 'p3', Teams.TeamA);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p3');

    match = addPlayer(match, 'p4', Teams.TeamB, dealOrder);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p4 (deal)');

    match = placeBid(match, 'p1', Bid.Thirty);
    expectMatchesFixtureStep(match, steps[i++], 'bid p1 Thirty');
    match = placeBid(match, 'p2', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p2 Pass');
    match = placeBid(match, 'p3', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p3 Pass');
    match = placeBid(match, 'p4', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p4 Pass');

    match = setTrump(match, 'p1', Suit.Low);
    expectMatchesFixtureStep(match, steps[i++], 'setTrump p1 Low');

    // Trick 1: p3 (p1's partner) never plays - the Low skip rule.
    match = playDomino(match, 'p1', createDomino(6, 6));
    expectMatchesFixtureStep(match, steps[i++], 'playDomino p1 {6,6}');
    match = playDomino(match, 'p2', createDomino(1, 6));
    expectMatchesFixtureStep(match, steps[i++], 'playDomino p2 {1,6}');
    match = playDomino(match, 'p4', createDomino(2, 6));
    expectMatchesFixtureStep(match, steps[i++], 'playDomino p4 {2,6}');

    // p1 (the Low bidder) won trick 1 -> the OTHER team (TeamB) wins the game immediately.
    // The C# app doesn't stop play once a game's winner is set mid-hand, so play continues.
    expect(gameWinningTeam(match.currentGame), 'after trick 1: gameWinningTeam').toBe(Teams.TeamB);

    // Trick 2: same skip pattern.
    match = playDomino(match, 'p1', createDomino(5, 5));
    expectMatchesFixtureStep(match, steps[i++], 'playDomino p1 {5,5}');
    match = playDomino(match, 'p2', createDomino(0, 5));
    expectMatchesFixtureStep(match, steps[i++], 'playDomino p2 {0,5}');
    match = playDomino(match, 'p4', createDomino(3, 5));
    expectMatchesFixtureStep(match, steps[i++], 'playDomino p4 {3,5}');

    expect(i).toBe(steps.length);
    expect(gameWinningTeam(match.currentGame), 'final step: gameWinningTeam').toBe(Teams.TeamB);
  });
});

describe('characterization: plunge-game fixture', () => {
  const steps = loadFixture('plunge-game.json');
  const dealOrder = dealOrderFrom([
    [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [1, 2],
    [1, 3], [1, 4], [1, 5], [1, 6], [2, 3], [2, 4], [2, 5],
    [0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6],
    [2, 6], [3, 4], [3, 5], [3, 6], [4, 5], [4, 6], [5, 6],
  ]);

  it('replays the exact C# scenario, routing setTrump/play through the Plunge bidder\'s partner', () => {
    expect(steps).toHaveLength(17);
    let i = 0;

    let match = createMatch('p1');
    expectMatchesFixtureStep(match, steps[i++], 'create');

    match = addPlayer(match, 'p2', Teams.TeamB);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p2');

    match = addPlayer(match, 'p3', Teams.TeamA);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p3');

    match = addPlayer(match, 'p4', Teams.TeamB, dealOrder);
    expectMatchesFixtureStep(match, steps[i++], 'addPlayer p4 (deal)');

    match = placeBid(match, 'p1', Bid.Plunge);
    expectMatchesFixtureStep(match, steps[i++], 'bid p1 Plunge');
    match = placeBid(match, 'p2', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p2 Pass');
    match = placeBid(match, 'p3', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p3 Pass');
    match = placeBid(match, 'p4', Bid.Pass);
    expectMatchesFixtureStep(match, steps[i++], 'bid p4 Pass');

    // Core behavior this fixture proves: after all 4 bids, currentPlayerId is p3 (p1's partner
    // - Plunge routes trump-setting/play through the bidder's partner, not the bidder). Already
    // covered by expectMatchesFixtureStep above (compares against the fixture's recorded value),
    // asserted again explicitly here for clarity.
    expect(match.currentGame.biddingPlayerId).toBe('p1');
    expect(match.currentGame.currentPlayerId).toBe('p3');

    match = setTrump(match, 'p3', Suit.Sixes);
    expectMatchesFixtureStep(match, steps[i++], 'setTrump p3 Sixes');

    const plays: [string, [number, number]][] = [
      ['p3', [6, 6]], ['p4', [2, 6]], ['p1', [0, 6]], ['p2', [1, 6]],
      ['p3', [5, 5]], ['p4', [3, 5]], ['p1', [0, 5]], ['p2', [1, 5]],
    ];

    for (const [playerId, [top, bottom]] of plays) {
      match = playDomino(match, playerId, createDomino(top, bottom));
      expectMatchesFixtureStep(match, steps[i++], `playDomino ${playerId} {${top},${bottom}}`);
    }

    expect(i).toBe(steps.length);
    // Only 2 of what would need to be a full hand's tricks were recorded. Plunge's adjustedBid
    // is 169 (the enum value itself - 169 % 42 !== 0, so the "%42===0 -> 42" normalization never
    // applies to it), so the bidding team can never cross that threshold in 2 tricks, and the
    // other team hasn't won a trick either.
    expect(gameWinningTeam(match.currentGame)).toBeNull();
  });
});
