name: CD-Heroku

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_fortytwogame:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'fortytwogame' }}
        AUTH0_CLIENTID: ${{ secrets.AUTH0_CLIENTID }}
      run: |
        cd ./
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker build --build-arg Auth0_ClientId=$AUTH0_CLIENTID -t registry.heroku.com/${{ env.APP_NAME }}/web .
        docker push registry.heroku.com/${{ env.APP_NAME }}/web
        heroku container:release web -a $APP_NAME